server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: restapi
          uri: http://localhost:8011
          predicates:
            - Path=/rest/**
        - id: serviceapi
          uri: lb://serviceapi
          predicates:
            - Path=/flight/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 30 # eureka에게 서비스 정보를 가져오는 주기
    disable-delta: true # eureka에게 서비스 정보를 가져올때 변경된 내용만 가져온다. (false로 하면 전체를 가져오기에 대역폭 낭비이다.)

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: true # default: true